---
title: "Nossas postagens"
output: html_document
buildDrafts: true
---

# [Alerta de publicação em periódico](/2026/06/20/alerta-de-publicação-em-periódico/)

# [IPPAC registra aumento de preços de produtos agrícolas em junho](/2026/06/09/ippac-registra-aumento-de-preços-de-produtos-agrícolas-em-junho/)


# [Pesquisadores do NIPE tem trabalho aprovado para apresentação no XXIX Encontro de Economia da Região Sul](/2026/05/26/pesquisadores-do-nipe-tem-trabalho-aprovado-para-apresentação-no-xxix-encontro-de-economia-da-região-sul/)

# [Alerta de seminário de pesquisa](/2026/05/25/alerta-de-seminários-de-pesquisa/)

# [IPPAC registra aumento de preços de produtos agrícolas em maio](/2026/05/11/ippac-registra-aumento-de-preços-de-produtos-agrícolas-em-maio/)

# [IPPAC registra aumento de preços de produtos agrícolas em abril](/2026/04/09/ippac-registra-aumento-de-preços-de-produtos-agrícolas-em-abril/)

# [IPPAC registra aumento de preços de produtos agrícolas em março](/2026/03/09/ippac-registra-aumento-de-preços-de-produtos-agrícolas-em-março/)

# [IPPAC registra aumento de preços de produtos agrícolas em fevereiro](/2026/02/06/ippac-registra-aumento-de-preços-de-produtos-agrícolas-em-fevereiro/)

# [Discente do NIPE é aprovado em programa de pós-graduação da UFV](/2025/12/22/discente-do-nipe-é-aprovado-em-programa-de-pós-graduação-da-ufv/)

# [Alerta de seminário de pesquisa](/2025/10/30/alerta-de-seminários-de-pesquisa/)

# [Alerta de seminário de pesquisa](/2025/10/09/alerta-de-seminários-de-pesquisa/)

# [Alerta de seminário de pesquisa](/2025/09/24/alerta-de-seminários-de-pesquisa/)

# [Alerta de participação em evento](/2025/09/22/alerta-de-participação-em-evento/)

# [Alerta de publicação em periódico](/2025/09/22/alerta-de-publicação-em-periódico/)

# [Alerta de publicação em periódico](/2025/08/08/alerta-de-publicação-em-periódico/)

# [Alerta de publicação em periódico](/2025/07/20/alerta-de-publicação-em-periódico/)

# [Pesquisadores do NIPE participarão do VI EEA-SE](/2025/06/26/pesquisadores-do-nipe-participarão-do-vi-eea-se/)


# [Alerta de publicação em periódico](/2025/06/12/alerta-de-publicação-em-periódico/)

# [Alerta de seminário de pesquisa](/2025/06/03/alerta-de-seminários-de-pesquisa/)

# [Boas vindas aos estudantes que ingressaram na equipe do NIPE](/2025/05/13/boas-vindas-aos-estudantes-que-ingressaram-na-equipe-do-nipe/)

# [NIPE conquista bolsa de produtividade em pesquisa](/2025/05/08/nipe-conquista-bolsa-de-produtividade-em-pesquisa/)

# [Alerta de publicação em periódico](/2025/05/06/alerta-de-publicação-em-periódico/)

# [Acessando as variações mensais do IPCA em R](/2025/01/02/acessando-as-variações-mensais-do-ipca-em-r/)
