---
title: "IPPAC registra aumento de preços de produtos agrícolas em maio"
#author: "Prof. Dr. Helson Gomes"
date: "2026-05-11"
output: html_document
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<hr>

O NIPE lançou nessa segunda-feira (11/05) os resultados do Índice de Preços de Produtos Agrícolas do Cariri (IPPAC) referentes ao mês de maio de 2026. De acordo com os resultados, ambas as cestas de produtos (frutas e hortaliças)
apresentaram um aumento de preços entre abril e maio, com a cesta de hortaliças apresentando o aumento mais expressivo. 
Em comparação com a primeira semana de abril de 2026, o IPPAC registrou um aumento de 1.45% no preço das frutas e um aumento de 12.80% no preço das hortaliças. Destaca-se o aumento expressivo no preço indiviual de produtos como a cenoura, a beterraba e a cebola. Como o aumento no preço médio de ambas as cestas, a variação média geral dos preços dos produtos agrícolas na primeira semana de maio foi positiva e alcançou cerca de 7.72% em relação ao mesmo período do mês anterior. Desde o início do monitoramento, o IPPAC registra um aumento de aproximadamente 11.97% nos preços dos produtos agrícolas, com o preço médio das frutas recuando 5.58% e o preço médio das hortaliças avançando cerca de 29.52%. Clique [aqui](https://nipe-urca.netlify.app/ippac/home) para maiores detalhes.