---
title: "NIPE conquista bolsa de produtividade em pesquisa"
#author: "Prof. Dr. Helson Gomes"
date: "2025-05-08"
output: html_document
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<hr>

O Núcleo Integrado de Pesquisa Econômica foi agraciado com uma bolsa de produtividade em pesquisa no *programa de bolsa de produtividade em pesquisa, estímulo à interiorização e inovação tecnológica - BPI* da Fundação Cearense de Apoio ao Desenvolvimento Científico e Tecnológico (Funcap), regido pelo [edital 11/2024](https://montenegro.funcap.ce.gov.br/sugba/edital/684.pdf). O projeto intitulado "***Medindo a alocação ótima de enfermos entre os municípios do estado do Ceará***", de autoria do [Prof. Helson Gomes de Souza](helsongsouza.netlify.app) foi contemplado na categoria BPI-2, que englobou os profissionais com no máximo cinco anos após a conclusão do doutorado e com regime de trabalho de 40 horas semanais. O objetivo central do projeto é indicar qual o melhor estabelecimento de saúde para onde os pacientes devem ser enviados - quando não há opções locais de tratamento - de maneira a minimizar os custos do transporte dos pacientes, os custos de tratamento e perdas de bem-estar dos enfermos nos municípios cearenses. Clique [aqui](https://montenegro.funcap.ce.gov.br/sugba/edital/resultados/751.pdf) para acessar o resultado da chamada na íntegra.

<hr>